Feature/21 sign in page
Abd-K/goGedit-api pull request #8
Opened 2023-08-07 17:30 UTC by abdulalghali

2023-08-07 17:40 UTC, ahmadalghali requested changes

2023-08-07 17:40 UTC, ahmadalghali commented on src/main/java/com/Gogedit/controller/AuthController.java
> +        return userService.getUser(userSignInRequestDTO);
instead of using the userService in authController, have an AuthService class

authService.register()

authService.signIn()

inside the authService you can utilise the userService to do fetch a user or create a user

2023-08-07 17:40 UTC, ahmadalghali commented on src/main/java/com/Gogedit/service/UserService.java
> +    Optional<AppUser> userOptional =
you may be repeating this logic multiple times throught the project, create a UserNotFoundException class in exception folder, and look at how Post, Community, Comment handleif db returns null when we get by id.

Use this as an example:

 public Post getPostById(String postId) {
    return postRepository.findById(postId)
            .orElseThrow(() -> new PostNotFoundException(postId));
  }

2023-08-07 17:41 UTC, ahmadalghali commented on src/main/java/com/Gogedit/controller/AuthController.java
> +    @GetMapping("sign-in")
use PostMapping for signIn and add missing '/'

2023-08-10 16:23 UTC, abdulalghali commented on src/main/java/com/Gogedit/controller/AuthController.java
> +    @GetMapping("sign-in")
done

2023-08-11 02:43 UTC, ahmadalghali commented on src/main/java/com/Gogedit/controller/AuthController.java
> +    @GetMapping("sign-in")
you need to push your changes, as they appear to still be local

2023-08-11 19:40 UTC, abdulalghali commented on src/main/java/com/Gogedit/service/UserService.java
> +    Optional<AppUser> userOptional =
done

2023-08-14 21:38 UTC, abdulalghali commented on src/main/java/com/Gogedit/controller/AuthController.java
> +        return userService.getUser(userSignInRequestDTO);
done

2023-08-14 22:11 UTC, ahmadalghali approved these changes
LGTM

2023-08-14 22:11 UTC, merged